//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSPDetail
    {
        public int id { get; set; }
        public string UserId { get; set; }
        public string Name { get; set; }
        public string CreateDate { get; set; }
        public byte[] Finger1 { get; set; }
        public byte[] Finger2 { get; set; }
        public byte[] Finger3 { get; set; }
        public byte[] Finger4 { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> UserTypeId { get; set; }
    }
}
