//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSPPunch
    {
        public int id { get; set; }
        public string CreateDate { get; set; }
        public string PunchIn { get; set; }
        public string PunchOut { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
